<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActionPlanTemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('action_plan_templates')->insert([
            [
                'code' => '1.1.1',
                'name' => 'Revisión de las actividades del plan de acción y anexos (formatos)',
                'description' => 'Registra estado de Revisión de las actividades del plan de acción y anexos (formatos)',
                'default_responsible' => 'Comisión PGE - SIS',
                'predecessor_action' => null,
                'default_business_days' => 1,
                'section' => '1.1 - Aprobación del plan de acción y formatos',
                'order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.1.2',
                'name' => 'Aprobación del plan de acción y anexos (formatos)',
                'description' => 'Registrar Aprobación del plan de acción anexos (formatos)',
                'default_responsible' => 'Comisión PGE - SIS',
                'predecessor_action' => '1.1.1',
                'default_business_days' => 1,
                'section' => '1.1 - Aprobación del plan de acción y formatos',
                'order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.2.1',
                'name' => 'Sesión de los responsables de presupuesto para la definición de plazos',
                'description' => 'Registrar Sesión de los responsables de presupuesto para la definición de plazos',
                'default_responsible' => 'PGE/OPP, SIS/OPP',
                'predecessor_action' => '1.1.2',
                'default_business_days' => 1,
                'section' => '1.2 - Transferencia de recursos presupuestarios',
                'order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.2.2',
                'name' => 'Solicitud de información del anexo 17',
                'description' => 'Registrar Solicitud de información del anexo 17',
                'default_responsible' => 'PGE/OPP, SIS/OPP',
                'predecessor_action' => '1.2.1',
                'default_business_days' => 1,
                'section' => '1.2 - Transferencia de recursos presupuestarios',
                'order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.2.3',
                'name' => 'Remisión de información del anexo 17',
                'description' => 'Registrar Remisión de información del anexo 17',
                'default_responsible' => 'PGE/OPP, SIS/OPP',
                'predecessor_action' => '1.2.2',
                'default_business_days' => 1,
                'section' => '1.2 - Transferencia de recursos presupuestarios',
                'order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.2.4',
                'name' => 'Cierre de transferencia de presupuesto (suscripción de acta)',
                'description' => 'Registrar Cierre de transferencia de presupuesto (suscripción de acta)',
                'default_responsible' => 'PGE/OPP, SIS/OPP',
                'predecessor_action' => '1.2.3',
                'default_business_days' => 1,
                'section' => '1.2 - Transferencia de recursos presupuestarios',
                'order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.2.5',
                'name' => 'Elaboración y remisión del proyecto de decreto supremo (DS)',
                'description' => 'Registrar Elaboración y remisión del proyecto de decreto supremo (DS)',
                'default_responsible' => 'PGE/OPP, SIS/OPP',
                'predecessor_action' => '1.2.4',
                'default_business_days' => 1,
                'section' => '1.2 - Transferencia de recursos presupuestarios',
                'order' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.2.6',
                'name' => 'Aprobación y publicación del DS',
                'description' => 'Registrar Aprobación y publicación del DS',
                'default_responsible' => 'PGE/OPP, SIS/OPP',
                'predecessor_action' => '1.2.5',
                'default_business_days' => 1,
                'section' => '1.2 - Transferencia de recursos presupuestarios',
                'order' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.3.1',
                'name' => 'Sesión de los responsables de recursos humanos para la definición de plazos',
                'description' => 'Registrar Sesión de los responsables de recursos humanos para la definición de plazos',
                'default_responsible' => 'PGE/OA, SIS/UFRRHH',
                'predecessor_action' => '1.1.2',
                'default_business_days' => 1,
                'section' => '1.3 - Transferencia de recursos humanos',
                'order' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.3.2',
                'name' => 'Solicitud de información de los anexos 1 a 3',
                'description' => 'Registrar Solicitud de información de los anexos 1 a 3',
                'default_responsible' => 'PGE/OA, SIS/UFRRHH',
                'predecessor_action' => '1.3.1',
                'default_business_days' => 1,
                'section' => '1.3 - Transferencia de recursos humanos',
                'order' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.3.3',
                'name' => 'Remisión de información de los anexos 1 al 3',
                'description' => 'Registrar Remisión de información de los anexos 1 al 3',
                'default_responsible' => 'PGE/OA, SIS/UFRRHH',
                'predecessor_action' => '1.3.2',
                'default_business_days' => 1,
                'section' => '1.3 - Transferencia de recursos humanos',
                'order' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.3.4',
                'name' => 'Validación de la información de los anexos 1 al 3',
                'description' => 'Registrar Validación de la información de los anexos 1 al 3',
                'default_responsible' => 'PGE/OA, SIS/UFRRHH',
                'predecessor_action' => '1.3.3',
                'default_business_days' => 1,
                'section' => '1.3 - Transferencia de recursos humanos',
                'order' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.3.5',
                'name' => 'Remisión de los legajos de personal activo',
                'description' => 'Registrar Remisión de los legajos de personal activo',
                'default_responsible' => 'PGE/OA, SIS/UFRRHH',
                'predecessor_action' => '1.3.4',
                'default_business_days' => 1,
                'section' => '1.3 - Transferencia de recursos humanos',
                'order' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.3.6',
                'name' => 'Validación de los legajos de personal activo',
                'description' => 'Registrar Validación de los legajos de personal activo',
                'default_responsible' => 'PGE/OA, SIS/UFRRHH',
                'predecessor_action' => '1.3.5',
                'default_business_days' => 1,
                'section' => '1.3 - Transferencia de recursos humanos',
                'order' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.3.7',
                'name' => 'Remisión de informe por subsistemas de gestión de recursos humanos',
                'description' => 'Registrar Remisión de informe por subsistemas de gestión de recursos humanos',
                'default_responsible' => 'PGE/OA, SIS/UFRRHH',
                'predecessor_action' => '1.3.6',
                'default_business_days' => 1,
                'section' => '1.3 - Transferencia de recursos humanos',
                'order' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.3.8',
                'name' => 'Validación de informe por subsistemas de gestión de recursos humanos',
                'description' => 'Registrar Validación de informe por subsistemas de gestión de recursos humanos',
                'default_responsible' => 'PGE/OA, SIS/UFRRHH',
                'predecessor_action' => '1.3.7',
                'default_business_days' => 1,
                'section' => '1.3 - Transferencia de recursos humanos',
                'order' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.3.9',
                'name' => 'Cierre de transferencia de recursos humanos (suscripción de acta)',
                'description' => 'Registrar Cierre de transferencia de recursos humanos (suscripción de acta)',
                'default_responsible' => 'PGE/OA, SIS/UFRRHH',
                'predecessor_action' => '1.2.6, 1.3.8',
                'default_business_days' => 1,
                'section' => '1.3 - Transferencia de recursos humanos',
                'order' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Continúa con todas las demás acciones...
            // Por brevedad, aquí muestro solo algunas. El archivo completo tendría todas las 44 acciones
        ]);
    }
}
