<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActionPlanTemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rows = [
            [
                'code' => '1.1.1',
                'name' => 'Revisión de las actividades del plan de acción y anexos (formatos)',
                'description' => 'Registra estado de Revisión de las actividades del plan de acción y anexos (formatos)',
                'default_responsible' => 'Comisión PGE - SIS',
                'predecessor_action' => null,
                'default_business_days' => 1,
                'section' => '1.1 - Aprobación del plan de acción y formatos',
                'order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.1.2',
                'name' => 'Aprobación del plan de acción y anexos (formatos)',
                'description' => 'Registrar Aprobación del plan de acción anexos (formatos)',
                'default_responsible' => 'Comisión PGE - SIS',
                'predecessor_action' => '1.1.1',
                'default_business_days' => 1,
                'section' => '1.1 - Aprobación del plan de acción y formatos',
                'order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.2.1',
                'name' => 'Sesión de los responsables de presupuesto para la definición de plazos',
                'description' => 'Registrar Sesión de los responsables de presupuesto para la definición de plazos',
                'default_responsible' => 'PGE/OPP, SIS/OPP',
                'predecessor_action' => '1.1.2',
                'default_business_days' => 1,
                'section' => '1.2 - Transferencia de recursos presupuestarios',
                'order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.2.2',
                'name' => 'Solicitud de información del anexo 17',
                'description' => 'Registrar Solicitud de información del anexo 17',
                'default_responsible' => 'PGE/OPP, SIS/OPP',
                'predecessor_action' => '1.2.1',
                'default_business_days' => 1,
                'section' => '1.2 - Transferencia de recursos presupuestarios',
                'order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.2.3',
                'name' => 'Remisión de información del anexo 17',
                'description' => 'Registrar Remisión de información del anexo 17',
                'default_responsible' => 'PGE/OPP, SIS/OPP',
                'predecessor_action' => '1.2.2',
                'default_business_days' => 1,
                'section' => '1.2 - Transferencia de recursos presupuestarios',
                'order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.2.4',
                'name' => 'Cierre de transferencia de presupuesto (suscripción de acta)',
                'description' => 'Registrar Cierre de transferencia de presupuesto (suscripción de acta)',
                'default_responsible' => 'PGE/OPP, SIS/OPP',
                'predecessor_action' => '1.2.3',
                'default_business_days' => 1,
                'section' => '1.2 - Transferencia de recursos presupuestarios',
                'order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.2.5',
                'name' => 'Elaboración y remisión del proyecto de decreto supremo (DS)',
                'description' => 'Registrar Elaboración y remisión del proyecto de decreto supremo (DS)',
                'default_responsible' => 'PGE/OPP, SIS/OPP',
                'predecessor_action' => '1.2.4',
                'default_business_days' => 1,
                'section' => '1.2 - Transferencia de recursos presupuestarios',
                'order' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.2.6',
                'name' => 'Aprobación y publicación del DS',
                'description' => 'Registrar Aprobación y publicación del DS',
                'default_responsible' => 'PGE/OPP, SIS/OPP',
                'predecessor_action' => '1.2.5',
                'default_business_days' => 1,
                'section' => '1.2 - Transferencia de recursos presupuestarios',
                'order' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.3.1',
                'name' => 'Sesión de los responsables de recursos humanos para la definición de plazos',
                'description' => 'Registrar Sesión de los responsables de recursos humanos para la definición de plazos',
                'default_responsible' => 'PGE/OA, SIS/UFRRHH',
                'predecessor_action' => '1.1.2',
                'default_business_days' => 1,
                'section' => '1.3 - Transferencia de recursos humanos',
                'order' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.3.2',
                'name' => 'Solicitud de información de los anexos 1 a 3',
                'description' => 'Registrar Solicitud de información de los anexos 1 a 3',
                'default_responsible' => 'PGE/OA, SIS/UFRRHH',
                'predecessor_action' => '1.3.1',
                'default_business_days' => 1,
                'section' => '1.3 - Transferencia de recursos humanos',
                'order' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.3.3',
                'name' => 'Remisión de información de los anexos 1 al 3',
                'description' => 'Registrar Remisión de información de los anexos 1 al 3',
                'default_responsible' => 'PGE/OA, SIS/UFRRHH',
                'predecessor_action' => '1.3.2',
                'default_business_days' => 1,
                'section' => '1.3 - Transferencia de recursos humanos',
                'order' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.3.4',
                'name' => 'Validación de la información de los anexos 1 al 3',
                'description' => 'Registrar Validación de la información de los anexos 1 al 3',
                'default_responsible' => 'PGE/OA, SIS/UFRRHH',
                'predecessor_action' => '1.3.3',
                'default_business_days' => 1,
                'section' => '1.3 - Transferencia de recursos humanos',
                'order' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.3.5',
                'name' => 'Remisión de los legajos de personal activo',
                'description' => 'Registrar Remisión de los legajos de personal activo',
                'default_responsible' => 'PGE/OA, SIS/UFRRHH',
                'predecessor_action' => '1.3.4',
                'default_business_days' => 1,
                'section' => '1.3 - Transferencia de recursos humanos',
                'order' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.3.6',
                'name' => 'Validación de los legajos de personal activo',
                'description' => 'Registrar Validación de los legajos de personal activo',
                'default_responsible' => 'PGE/OA, SIS/UFRRHH',
                'predecessor_action' => '1.3.5',
                'default_business_days' => 1,
                'section' => '1.3 - Transferencia de recursos humanos',
                'order' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.3.7',
                'name' => 'Remisión de informe por subsistemas de gestión de recursos humanos',
                'description' => 'Registrar Remisión de informe por subsistemas de gestión de recursos humanos',
                'default_responsible' => 'PGE/OA, SIS/UFRRHH',
                'predecessor_action' => '1.3.6',
                'default_business_days' => 1,
                'section' => '1.3 - Transferencia de recursos humanos',
                'order' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.3.8',
                'name' => 'Validación de informe por subsistemas de gestión de recursos humanos',
                'description' => 'Registrar Validación de informe por subsistemas de gestión de recursos humanos',
                'default_responsible' => 'PGE/OA, SIS/UFRRHH',
                'predecessor_action' => '1.3.7',
                'default_business_days' => 1,
                'section' => '1.3 - Transferencia de recursos humanos',
                'order' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.3.9',
                'name' => 'Cierre de transferencia de recursos humanos (suscripción de acta)',
                'description' => 'Registrar Cierre de transferencia de recursos humanos (suscripción de acta)',
                'default_responsible' => 'PGE/OA, SIS/UFRRHH',
                'predecessor_action' => '1.2.6, 1.3.8',
                'default_business_days' => 1,
                'section' => '1.3 - Transferencia de recursos humanos',
                'order' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // ==========================================
            // 1.4 - Transferencia de bienes (12 acciones)
            // ==========================================
            [
                'code' => '1.4.1',
                'name' => 'Sesión de los responsables de bienes para la definición de plazos',
                'description' => 'Registrar Sesión de los responsables de bienes para la definición de plazos',
                'default_responsible' => 'PGE/OGA, SIS/OGA',
                'predecessor_action' => '1.1.2',
                'default_business_days' => 1,
                'section' => '1.4 - Transferencia de bienes',
                'order' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.4.2',
                'name' => 'Solicitud de información de los anexos 4 a 10',
                'description' => 'Registrar Solicitud de información de los anexos 4 a 10',
                'default_responsible' => 'PGE/OGA, SIS/OGA',
                'predecessor_action' => '1.4.1',
                'default_business_days' => 1,
                'section' => '1.4 - Transferencia de bienes',
                'order' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.4.3',
                'name' => 'Entrega de información de los anexos 4 a 10',
                'description' => 'Registrar Entrega de información de los anexos 4 a 10',
                'default_responsible' => 'PGE/OGA, SIS/OGA',
                'predecessor_action' => '1.4.2',
                'default_business_days' => 1,
                'section' => '1.4 - Transferencia de bienes',
                'order' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.4.4.1',
                'name' => 'Verificación física de bienes muebles',
                'description' => 'Registrar Verificación física de bienes muebles',
                'default_responsible' => 'PGE/OGA, SIS/OGA',
                'predecessor_action' => '1.4.3',
                'default_business_days' => 2,
                'section' => '1.4 - Transferencia de bienes',
                'order' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.4.4.2',
                'name' => 'Solicitud de transferencia de bienes muebles',
                'description' => 'Registrar Solicitud de transferencia de bienes muebles',
                'default_responsible' => 'PGE/OGA, SIS/OGA',
                'predecessor_action' => '1.4.4.1',
                'default_business_days' => 1,
                'section' => '1.4 - Transferencia de bienes',
                'order' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.4.4.3',
                'name' => 'Evaluación e informe técnico de bienes muebles',
                'description' => 'Registrar Evaluación e informe técnico de bienes muebles',
                'default_responsible' => 'PGE/OGA, SIS/OGA',
                'predecessor_action' => '1.4.4.2',
                'default_business_days' => 2,
                'section' => '1.4 - Transferencia de bienes',
                'order' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.4.4.4',
                'name' => 'Aprobación de resolución de transferencia de bienes',
                'description' => 'Registrar Aprobación de resolución de transferencia de bienes',
                'default_responsible' => 'PGE/OGA, SIS/OGA',
                'predecessor_action' => '1.4.4.3',
                'default_business_days' => 1,
                'section' => '1.4 - Transferencia de bienes',
                'order' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.4.4.5',
                'name' => 'Acta de entrega-recepción de bienes muebles',
                'description' => 'Registrar Acta de entrega-recepción de bienes muebles',
                'default_responsible' => 'PGE/OGA, SIS/OGA',
                'predecessor_action' => '1.4.4.4',
                'default_business_days' => 1,
                'section' => '1.4 - Transferencia de bienes',
                'order' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.4.5',
                'name' => 'Coordinación y suscripción de convenio de uso de inmueble',
                'description' => 'Registrar Coordinación y suscripción de convenio de uso de inmueble',
                'default_responsible' => 'PGE/OGA, SIS/OGA',
                'predecessor_action' => '1.4.4.5',
                'default_business_days' => 3,
                'section' => '1.4 - Transferencia de bienes',
                'order' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.4.6',
                'name' => 'Cierre de transferencia de bienes (suscripción de acta)',
                'description' => 'Registrar Cierre de transferencia de bienes (suscripción de acta)',
                'default_responsible' => 'PGE/OGA, SIS/OGA',
                'predecessor_action' => '1.4.5',
                'default_business_days' => 1,
                'section' => '1.4 - Transferencia de bienes',
                'order' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // ==========================================
            // 1.5 - Transferencia del acervo documentario (6 acciones)
            // ==========================================
            [
                'code' => '1.5.1',
                'name' => 'Sesión de los responsables de archivo para la definición de plazos',
                'description' => 'Registrar Sesión de los responsables de archivo para la definición de plazos',
                'default_responsible' => 'PGE/SGA, SIS/ARCHIVO',
                'predecessor_action' => '1.1.2',
                'default_business_days' => 1,
                'section' => '1.5 - Transferencia del acervo documentario',
                'order' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.5.2',
                'name' => 'Solicitud de información de los anexos 15 a 16',
                'description' => 'Registrar Solicitud de información de los anexos 15 a 16',
                'default_responsible' => 'PGE/SGA, SIS/ARCHIVO',
                'predecessor_action' => '1.5.1',
                'default_business_days' => 1,
                'section' => '1.5 - Transferencia del acervo documentario',
                'order' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.5.3',
                'name' => 'Entrega de información de los anexos 15 a 16',
                'description' => 'Registrar Entrega de información de los anexos 15 a 16',
                'default_responsible' => 'PGE/SGA, SIS/ARCHIVO',
                'predecessor_action' => '1.5.2',
                'default_business_days' => 2,
                'section' => '1.5 - Transferencia del acervo documentario',
                'order' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.5.4',
                'name' => 'Validación del archivo central',
                'description' => 'Registrar Validación del archivo central',
                'default_responsible' => 'PGE/SGA, SIS/ARCHIVO',
                'predecessor_action' => '1.5.3',
                'default_business_days' => 2,
                'section' => '1.5 - Transferencia del acervo documentario',
                'order' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.5.5',
                'name' => 'Acta de entrega-recepción del acervo documentario',
                'description' => 'Registrar Acta de entrega-recepción del acervo documentario',
                'default_responsible' => 'PGE/SGA, SIS/ARCHIVO',
                'predecessor_action' => '1.5.4',
                'default_business_days' => 1,
                'section' => '1.5 - Transferencia del acervo documentario',
                'order' => 32,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.5.6',
                'name' => 'Cierre de transferencia del acervo documentario (suscripción de acta)',
                'description' => 'Registrar Cierre de transferencia del acervo documentario (suscripción de acta)',
                'default_responsible' => 'PGE/SGA, SIS/ARCHIVO',
                'predecessor_action' => '1.5.5',
                'default_business_days' => 1,
                'section' => '1.5 - Transferencia del acervo documentario',
                'order' => 33,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // ==========================================
            // 1.6 - Transferencia de activos informáticos (6 acciones)
            // ==========================================
            [
                'code' => '1.6.1',
                'name' => 'Sesión de los responsables de TI para la definición de plazos',
                'description' => 'Registrar Sesión de los responsables de TI para la definición de plazos',
                'default_responsible' => 'PGE/OTI, SIS/OTI',
                'predecessor_action' => '1.1.2',
                'default_business_days' => 1,
                'section' => '1.6 - Transferencia de activos informáticos',
                'order' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.6.2',
                'name' => 'Solicitud de información de los anexos 11 a 14',
                'description' => 'Registrar Solicitud de información de los anexos 11 a 14',
                'default_responsible' => 'PGE/OTI, SIS/OTI',
                'predecessor_action' => '1.6.1',
                'default_business_days' => 1,
                'section' => '1.6 - Transferencia de activos informáticos',
                'order' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.6.3',
                'name' => 'Entrega de información de los anexos 11 a 14',
                'description' => 'Registrar Entrega de información de los anexos 11 a 14',
                'default_responsible' => 'PGE/OTI, SIS/OTI',
                'predecessor_action' => '1.6.2',
                'default_business_days' => 2,
                'section' => '1.6 - Transferencia de activos informáticos',
                'order' => 36,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.6.4',
                'name' => 'Validación de los anexos de activos informáticos',
                'description' => 'Registrar Validación de los anexos de activos informáticos',
                'default_responsible' => 'PGE/OTI, SIS/OTI',
                'predecessor_action' => '1.6.3',
                'default_business_days' => 2,
                'section' => '1.6 - Transferencia de activos informáticos',
                'order' => 37,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.6.5',
                'name' => 'Acuerdo de continuidad operativa de sistemas',
                'description' => 'Registrar Acuerdo de continuidad operativa de sistemas',
                'default_responsible' => 'PGE/OTI, SIS/OTI',
                'predecessor_action' => '1.6.4',
                'default_business_days' => 2,
                'section' => '1.6 - Transferencia de activos informáticos',
                'order' => 38,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.6.6',
                'name' => 'Cierre de transferencia de activos informáticos (suscripción de acta)',
                'description' => 'Registrar Cierre de transferencia de activos informáticos (suscripción de acta)',
                'default_responsible' => 'PGE/OTI, SIS/OTI',
                'predecessor_action' => '1.6.5',
                'default_business_days' => 1,
                'section' => '1.6 - Transferencia de activos informáticos',
                'order' => 39,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // ==========================================
            // 1.7 - Cierre de transferencia (3 acciones)
            // ==========================================
            [
                'code' => '1.7.1',
                'name' => 'Elaboración del informe de cierre de la transferencia',
                'description' => 'Registrar Elaboración del informe de cierre de la transferencia',
                'default_responsible' => 'Comisión PGE - SIS',
                'predecessor_action' => '1.3.9, 1.4.6, 1.5.6, 1.6.6',
                'default_business_days' => 3,
                'section' => '1.7 - Cierre de transferencia',
                'order' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.7.2',
                'name' => 'Aprobación del informe de cierre',
                'description' => 'Registrar Aprobación del informe de cierre',
                'default_responsible' => 'Comisión PGE - SIS',
                'predecessor_action' => '1.7.1',
                'default_business_days' => 2,
                'section' => '1.7 - Cierre de transferencia',
                'order' => 41,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '1.7.3',
                'name' => 'Cierre de transferencia de la entidad (suscripción de acta final)',
                'description' => 'Registrar Cierre de transferencia de la entidad (suscripción de acta final)',
                'default_responsible' => 'Comisión PGE - SIS',
                'predecessor_action' => '1.7.2',
                'default_business_days' => 1,
                'section' => '1.7 - Cierre de transferencia',
                'order' => 42,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Usar upsert para evitar errores por duplicados en la columna única 'code'
        DB::table('action_plan_templates')->upsert(
            $rows,
            ['code'], // unique by code
            [
                'name',
                'description',
                'default_responsible',
                'predecessor_action',
                'default_business_days',
                'section',
                'order',
                'updated_at'
            ]
        );
    }
}
